### ISSUE TITLE
Add support for keyframe animations

### ISSUE THREAD

**Issue by salutis** [conradev/CKShapeView#6]
`CKShapeView` doesn't play well with `UIView`'s `animateKeyframesWithDuration`.

**Comment by conradev** [comment]
It also doesn't play well with `UIViewAnimationOptionBeginFromCurrentState`. I'll have to investigate whether or not there is a way to do it with public APIs.

**Comment by salutis** [comment]
Created simpler version that works with `animateKeyframesWithDuration`:
https://github.com/salutis/ShapeView/blob/master/ShapeView.swift
Closing for now.
